name: Weekly License Header Check

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at 00:00 UTC

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run License Header Checker
        uses: dell/common-github-actions/license-checker@main
        with:
          autofix: false
